#Move/copy this to ~/.config/projLaunch/config.conf and update this comment

DIR_projLaunch="/Users/atulsingharora/Documents/GitHub/projLaunch"
DIR_Git="/Users/atulsingharora/Documents/Git"
DIR_GitHub="/Users/atulsingharora/Documents/GitHub"
DIR_iCloud="/Users/atulsingharora/Library/Mobile\ Documents/com\~apple\~CloudDocs"