#!/bin/bash
source ~/.config/projLaunch/config.conf

DIR_projA="$DIR_GitHub/spineless"
DIR_projB="$DIR_GitHub/incompetent-clowns.github.io"

open "$DIR_projA" "$DIR_projB"
code --new-window "$DIR_projA"
code --new-window "$DIR_projB"
# open -a "Visual Studio Code" "$DIR_projA"
# open -a "Visual Studio Code" "$DIR_projB"